services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
  kafka-broker1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-broker1
    ports:
      - '8097:8097'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8097,INTERNAL://kafka-broker1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  kafka-broker2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-broker2
    ports:
      - '8098:8098'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8098,INTERNAL://kafka-broker2:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  kafka-broker3:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka-broker3
    ports:
      - '8099:8099'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8099,INTERNAL://kafka-broker3:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
